logging:
  level:
    root: warn
    com.seliote.mlb: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%t] %-40.40logger{39} : %-0.-4096m%n'
  file:
    name: logs/mlb-web.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      total-size-cap: 500MB

management:
  endpoints:
    enabled-by-default: false

spring:
  main:
    banner-mode: log
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/music_linker?useSsl=false
    username: emanresu
    password: drowssap
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      connection-timeout: 3000
      max-lifetime: 1800000
      idle-timeout: 300000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: false
  redis:
    host: localhost
    port: 6379
    ssl: false
    database: 8
    username: root
    password: redis520!
  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092
    security:
      protocol: SASL_PLAINTEXT
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="root" password="kafka520!"'
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      max-poll-records: 20
      auto-commit-interval: 1000
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: true
