server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8

spring:
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: true
      FAIL_ON_UNKNOWN_PROPERTIES: true

