logging:
  level:
    com.seliote.mlb: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%5p) --- [%t] %-40.40logger{39} : %-0.-4096m%n'

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/music_linker?useSsl=false
    username: emanresu
    password: drowssap
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      connection-timeout: 3000
      max-lifetime: 1800000
      idle-timeout: 300000
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: false
  redis:
    host: localhost
    port: 6379
    database: 8
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
