logging:
  level:
    com.seliote.mlb: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%5p) --- [%t] %-40.40logger{39} : %m%n'

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

spring:
  datasource:
    name: mlb-mobile
    url: jdbc:mariadb://localhost:3306/music_linker?useSsl=false
    username: emanresu
    password: drowssap
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      connection-timeout: 3000
      max-lifetime: 1800000
      idle-timeout: 300000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: false
  redis:
    host: localhost
    port: 6379
    ssl: false
    database: 7
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: false
    properties:
      org.quartz:
        scheduler:
          instanceName: mlb-mobile-scheduler
          instanceId: AUTO
          batchTriggerAcquisitionMaxCount: 1
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          tablePrefix: QRTZ_
          isClustered: true
          clusterCheckinInterval: 15000
          useProperties: false
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 20

com.seliote.mlb:
  jws:
    secret: '01234567890123456789012345678901'
  minio:
    endpoint: http://localhost:9000
    access-key: root
    secret-key: Changeme_123
