server:
  port: 7000
  servlet:
    encoding:
      charset: UTF-8
    context-path: /m

spring:
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    log-resolved-exception: off
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: true
      FAIL_ON_UNKNOWN_PROPERTIES: true

com.seliote.mlb:
  default-user-avatar: 00000000-0000-0000-0000-000000000000.jpeg
  redis:
    namespace: mlb_m
    key-separator: ':'
  jws:
    iss: mlb-mobile
    valid-days: 30
  minio:
    bucket: mlb
    catalog:
      avatar: avatar
      music: music
    extension:
      img-png: png
      img-jpg: jpg
      img-jpeg: jpeg
      audio-mp3: mp3